[profile.default]
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
]
fs_permissions = [{ access = "read-write", path = ".secret"}, { access ="read", path="./out/"}]
gas_reports = ["*"]
ffi = true 

solc = "0.8.19"
optimize = true
optimizer_runs = 100000
via_ir = true

[rpc_endpoints]
#fuji = "${}"

[etherscan]
#fuji = { key = "${SNOWTRACE_API_KEY}" }

[fmt]
line_length = 120
multiline_func_header = "params_first"
number_underscore="thousands"
# handle sorting of imports